### ISSUE TITLE
Building in 64bit OS

### ISSUE THREAD

**Issue by 0none** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#4] opened 2021-02-12 16:35 UTC
Hi,

i've been trying to get the headless compile running for the 64 bit Raspberry Pi OS, but I keep getting errors like so:

```
In file included from /usr/lib/llvm-10/lib/clang/10.0.0/include/xmmintrin.h:13:
/usr/lib/llvm-10/lib/clang/10.0.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^

```

Is there a known way around this error?

**Comment by daviel** [comment] 2021-02-22 08:38
same for Ubuntu 64Bit

**Comment by irishgreencitrus** [comment] 2021-02-25 11:29
What version is this? I've managed to build them all here's the wetransfer link. I've also uploaded them to google drive and i'll add the link here shortly https://wetransfer.com/downloads/732cf71758bb8792ea9660c759d3b7fa20210225110741/203cdc900b955314bc06de5ceb70068e20210225110933/d24e03

**Comment by daviel** [comment] 2021-02-26 11:32
> What version is this? I've managed to build them all here's the wetransfer link. I've also uploaded them to google drive and i'll add the link here shortly https://wetransfer.com/downloads/732cf71758bb8792ea9660c759d3b7fa20210225110741/203cdc900b955314bc06de5ceb70068e20210225110933/d24e03

Could you tell us how you did that?

**Comment by hiulit** [comment] 2021-03-01 11:14
I really don't know. I haven't tried to compile for the 64 bit Raspberry Pi OS. I'll upload the binaries that @irishgreencitrus compiled for us when I have the time :)

**Comment by irishgreencitrus** [comment] 2021-03-03 10:55
I just compiled them on Ubuntu 20.10 server.

**Comment by hiulit** [comment] 2021-06-07 11:06
Sorry, @irishgreencitrus , would you mind sharing the 64 bit binaries? The WeTransfer doesn't work and I can't find the link to the Google Drive.

Thank you! :D

**Comment by irishgreencitrus** [comment] 2021-06-07 12:26
@hiulit Sure! I'll compile all of them now.

**Comment by frankhale** [comment] 2021-06-07 12:38
@irishgreencitrus are you going to compile the latest 3.3.2? Was just release a couple weeks ago.

**Comment by hiulit** [comment] 2021-06-07 12:41
Thank you @irishgreencitrus ! :D

BTW, are you compiling on the Pi itself or are you cross-compiling? If it's the later, I'm interested to know what toolchain are you using, because the one I'm using only compiles for 32 bits https://github.com/hiulit/cross-compile-godot-raspberry-pi

**Comment by irishgreencitrus** [comment] 2021-06-07 13:52
> Thank you @irishgreencitrus ! :D
> 
> BTW, are you compiling on the Pi itself or are you cross-compiling? If it's the later, I'm interested to know what toolchain are you using, because the one I'm using only compiles for 32 bits https://github.com/hiulit/cross-compile-godot-raspberry-pi

Compiling on 64bit Manjaro ARM minimal, on a Raspberry Pi 4 8GB

**Comment by irishgreencitrus** [comment] 2021-06-09 16:13
@hiulit I can only seem to compile server builds for 3.3-stable and upwards. Is there any changes to flags that you made after the update?

**Comment by irishgreencitrus** [comment] 2021-06-09 17:16
ah i found the logs.
```
                  ^
/usr/lib/clang/11.1.0/include/mmintrin.h:352:19: note: '__builtin_arm_addg' declared here
/usr/lib/clang/11.1.0/include/mmintrin.h:352:19: error: first argument of MTE builtin function must be a pointer ('__v8qi' (vector of 8 'char' values) invalid)
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^                    ~~~~~~~~~~~~
/usr/lib/clang/11.1.0/include/mmintrin.h:373:19: error: use of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_addg'?
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/usr/lib/clang/11.1.0/include/mmintrin.h:352:19: note: '__builtin_arm_addg' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/usr/lib/clang/11.1.0/include/mmintrin.h:373:19: error: first argument of MTE builtin function must be a pointer ('__v4hi' (vector of 4 'short' values) invalid)
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                  ^                    ~~~~~~~~~~~~
/usr/lib/clang/11.1.0/include/mmintrin.h:394:19: error: use of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^
/usr/lib/clang/11.1.0/include/mmintrin.h:352:19: note: '__builtin_arm_addg' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/usr/lib/clang/11.1.0/include/mmintrin.h:394:19: error: first argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^                    ~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
scons: *** [thirdparty/oidn/core/device.x11.opt.tools.64.llvm.o] Error 1
```

**Comment by irishgreencitrus** [comment] 2021-06-09 17:18
hmm interesting I also get the same error as OP. I'll see if i can find a fix
```
In file included from thirdparty/oidn/core/api.cpp:48:
In file included from thirdparty/oidn/core/device.h:19:
In file included from thirdparty/oidn/core/common.h:19:                                                                             In file included from thirdparty/oidn/common/platform.h:27:                                                                         In file included from /usr/lib/clang/11.1.0/include/xmmintrin.h:13:                                                                 /usr/lib/clang/11.1.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?                                                                                                                                  __builtin_ia32_emms();                                                                                                              ^                                                                                                                               /usr/lib/clang/11.1.0/include/mmintrin.h:33:5: note: '__builtin_isless' declared here                                               /usr/lib/clang/11.1.0/include/mmintrin.h:33:25: error: too few arguments to function call, expected 2, have 0                           __builtin_ia32_emms();                                                                                                                                  ^ 
```

**Comment by irishgreencitrus** [comment] 2021-06-09 18:10
Link for the rest of the builds
https://drive.google.com/drive/folders/1Bd9-G7sNE6hr5IBo8Peh_iFVqU_sIjZ1?usp=sharing

**Comment by hiulit** [comment] 2021-06-10 13:45
Thank you! I'll upload them right away!

BTW, I only upload the latest version of each minor release, in this case: `2.1.6`, `3.1.2` and `3.3.2`. So you can save some compilation hours next time ;)

P.S. Have you tried running the editor and export templates? Can you confirm that they work? Specially the editor, where there has been some improvements on the `3.3` version which makes it run very smooth, as oposed to the `3.2.1`, which works but it's not very snappy.

**Comment by hiulit** [comment] 2021-06-10 13:50
@irishgreencitrus Oh, I didn't see all the issues you were having when compiling `3.3` builds. I didn't have any issues using this tool to cross-compile from Linux x86_64 https://github.com/hiulit/cross-compile-godot-raspberry-pi (but it only works for 32 bits)

**Comment by polyrain** [comment] 2021-12-21 10:17
Following up on this, did anyone ever get it to compile on 64bit Raspberry Pi OS?

**Comment by hiulit** [comment] 2022-02-15 09:37
I'm waiting for the Godot team to release a the cross-compilation tools with 64 bits support.
But as Raspbian has 64 bits "official" support, I'll try and compile it on the Pi itself when I have the time.

**Comment by hiulit** [comment] 2022-02-16 11:13
I've succesfully compiled Godot 3.4.2 on my Pi 4 with Raspberry Pi OS.
I'm using Clang, which is not the best option. I'll try again with GCC and LTO, but I haven't had any success with this option on the PI, only when using cross-compilation.

**Comment by hiulit** [comment] 2022-02-17 10:14
Hey! I've successfully compiled Godot 3.4.2 using GCC and LTO on my Raspberry Pi 4GB with a 64GB SD card and a 16GB swap using Raspberry Pi OS 64 bits. It takes a loooot of time :)

**Comment by HansKillinger** [comment] 2022-02-21 18:09
@hiulit Any chance I can get the binaries for 3.4.2 arm64? I dont have an sd card big enough to compile, nor am I very proficient.

**Comment by HansKillinger** [comment] 2022-02-21 18:16
@hiulit Im getting a '-bash: ./godot_3.4.2-stable_rpi4_server_lto.bin: No such file or directory' error when trying to run on ubuntu arm64 for rpi4
I did have it working on armhf. Am I doing something wrong or missing something?

**Comment by hiulit** [comment] 2022-02-21 18:20
@HansKillinger those binaries are compiled for 32 bits. I'll upload the 64 bits later. But they are built on the latest Raspbian OS 64 bits so they might now work on lower versions of the OS  or other OS. I'm waiting for the Godot team to release 64 bit toolchains to cross-compile

**Comment by HansKillinger** [comment] 2022-02-21 18:37
@hiulit Ok. So you have working 64 bit binaries but haven't uploaded to github? Or do we have to wait for the toolchain to be released before getting a 64 bit binary? Just wondering if I should downgrade my OS back to 32 bit.

**Comment by HansKillinger** [comment] 2022-02-21 18:38
Im not too savvy when it comes to compiling :(

**Comment by hiulit** [comment] 2022-02-21 19:13
@HansKillinger I have them compiled but they might not work for your OS because they are built on the latest Raspbian OS 64 bits. I'll upload them here so you can test them.
I'm waiting for the 64 bit toolchain, because:
1. It's waaay quicker to compile
2. The binaries work for all OS

**Comment by HansKillinger** [comment] 2022-02-21 19:30
@hiulit Thanks a million! I will test and reply back to you with results.

**Comment by hiulit** [comment] 2022-02-21 19:53
There you go! https://drive.google.com/drive/folders/1YdoYAyNhFHsIiPQS67ifgiMM5OpmCpqM?usp=sharing

**Comment by hiulit** [comment] 2022-02-21 20:21
Btw, this is what I used to compile:

```
scons platform=x11 target=release_debug tools=yes use_lto=yes CCFLAGS="-march=armv8-a+fp+simd" arch="arm64" -j4
```

This is for the editor.

**Comment by HansKillinger** [comment] 2022-02-21 21:13
@hiulit I can confirm server is working under Ubuntu 20.04 arm64 :)

**Comment by hiulit** [comment] 2022-02-22 09:13
@HansKillinger Nice! I'm glad it's working! :)

**Comment by hiulit** [comment] 2022-03-03 14:07
Hey, could you the new 3.4.3 binaries for the Pi 4 64 bits? https://drive.google.com/drive/folders/1E2IgjWmr-7DyKG3Gx8Rfu6hwg170ship?usp=sharing
Thanks!

**Comment by hiulit** [comment] 2022-03-14 12:09
Hey! I've "officially" released 64-bits binaries for the Pi 4 https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi#343

**Comment by hiulit** [comment] 2022-03-14 16:14
I've also added instructions on how to compile on a Raspberry Pi 4 64 bits https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi/blob/main/COMPILING.md#raspberry-pi-4

**Comment by hiulit** [comment] 2022-03-14 16:15
I'll close this issue for now. Feel free to open it again if needed.

**Closed by hiulit** 2022-03-14 16:15 UTC
